/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelo.Producto;
import Modelo.Supermercado;
import java.util.TreeSet;


public class VistaMenuPrincipal extends javax.swing.JFrame {
    public static Supermercado supermercado = new Supermercado();
    /**
     * Creates new form VistaMenuPrincipal
     */
    public VistaMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        menuBar_principal = new javax.swing.JMenuBar();
        menu_administracion = new javax.swing.JMenu();
        mit_producto = new javax.swing.JMenuItem();
        menu_consultas = new javax.swing.JMenu();
        mit_nombre = new javax.swing.JMenuItem();
        mit_precio = new javax.swing.JMenuItem();
        mit_rubro = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 827, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 716, Short.MAX_VALUE)
        );

        menu_administracion.setText("Administracion");

        mit_producto.setText("Producto");
        mit_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mit_productoActionPerformed(evt);
            }
        });
        menu_administracion.add(mit_producto);

        menuBar_principal.add(menu_administracion);

        menu_consultas.setText("Consultas");

        mit_nombre.setText("Consulta por Nombre");
        menu_consultas.add(mit_nombre);

        mit_precio.setText("Consulta por Precio");
        menu_consultas.add(mit_precio);

        mit_rubro.setText("Consulta por Rubro");
        menu_consultas.add(mit_rubro);

        menuBar_principal.add(menu_consultas);

        setJMenuBar(menuBar_principal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mit_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mit_productoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        VistaGestionProductos  vistaGestionProductos = new VistaGestionProductos();
        escritorio.add(vistaGestionProductos);
        vistaGestionProductos.setVisible(true);
        escritorio.moveToFront(vistaGestionProductos);

    }//GEN-LAST:event_mit_productoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar menuBar_principal;
    private javax.swing.JMenu menu_administracion;
    private javax.swing.JMenu menu_consultas;
    private javax.swing.JMenuItem mit_nombre;
    private javax.swing.JMenuItem mit_precio;
    private javax.swing.JMenuItem mit_producto;
    private javax.swing.JMenuItem mit_rubro;
    // End of variables declaration//GEN-END:variables
}
