
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Alumno;
import Modelo.Materia;

/**
 *
 * @author Rickert
 */
public class AltaFormulario extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaFormulario
     */
    public AltaFormulario() {
        initComponents();
        cargarComboMaterias();
        cargarComboAlumnos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_inscripcion = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_seleccionMateria = new javax.swing.JLabel();
        lbl_seleccionAlumno = new javax.swing.JLabel();
        cb_materia = new javax.swing.JComboBox<>();
        cb_alumno = new javax.swing.JComboBox<>();
        btn_inscribir = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        pnl_inscripcion.setBackground(new java.awt.Color(204, 204, 204));

        lbl_titulo.setFont(new java.awt.Font("JetBrains Mono Medium", 0, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo.setText("Formulario de Inscripcion");

        lbl_seleccionMateria.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_seleccionMateria.setForeground(new java.awt.Color(0, 0, 0));
        lbl_seleccionMateria.setText("Elija una Materia:");

        lbl_seleccionAlumno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_seleccionAlumno.setForeground(new java.awt.Color(0, 0, 0));
        lbl_seleccionAlumno.setText("Elija un alumno:");

        cb_materia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_materiaActionPerformed(evt);
            }
        });

        cb_alumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_alumnoActionPerformed(evt);
            }
        });

        btn_inscribir.setText("Inscribir");
        btn_inscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inscribirActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_inscripcionLayout = new javax.swing.GroupLayout(pnl_inscripcion);
        pnl_inscripcion.setLayout(pnl_inscripcionLayout);
        pnl_inscripcionLayout.setHorizontalGroup(
            pnl_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_inscripcionLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pnl_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_seleccionAlumno)
                    .addComponent(lbl_seleccionMateria))
                .addGap(38, 38, 38)
                .addGroup(pnl_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_materia, 0, 110, Short.MAX_VALUE)
                    .addComponent(cb_alumno, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_inscripcionLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(pnl_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_inscripcionLayout.createSequentialGroup()
                        .addComponent(lbl_titulo)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_inscripcionLayout.createSequentialGroup()
                        .addComponent(btn_inscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        pnl_inscripcionLayout.setVerticalGroup(
            pnl_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_inscripcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titulo)
                .addGap(37, 37, 37)
                .addGroup(pnl_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_seleccionMateria)
                    .addGroup(pnl_inscripcionLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cb_materia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(pnl_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_alumno, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_seleccionAlumno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(pnl_inscripcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_inscribir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(pnl_inscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_inscripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_materiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_materiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_materiaActionPerformed

    private void cb_alumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_alumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_alumnoActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        
        pnl_inscripcion.removeAll();
        pnl_inscripcion.repaint();

        pnl_inscripcion.setVisible(false);
        this.dispose();
        
        
        
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_inscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inscribirActionPerformed
        
        RegistroPrincipal.resultadosInscripcion.add((Alumno)cb_alumno.getSelectedItem());
        
        for(Alumno prueba: RegistroPrincipal.resultadosInscripcion){
            
            System.out.println(prueba);
        }
        
        
                
    }//GEN-LAST:event_btn_inscribirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inscribir;
    private javax.swing.JButton btn_salir;
    private javax.swing.JComboBox<Alumno> cb_alumno;
    private javax.swing.JComboBox<String> cb_materia;
    private javax.swing.JLabel lbl_seleccionAlumno;
    private javax.swing.JLabel lbl_seleccionMateria;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_inscripcion;
    // End of variables declaration//GEN-END:variables

    private void cargarComboMaterias(){
      
        for(Materia materiaAgregada: RegistroPrincipal.materiasInscripcion){
            
            cb_materia.addItem(materiaAgregada.getNombreMateria());
        
        }
        
        
    };
    
    private void cargarComboAlumnos(){
        
        for(Alumno alumnoAgregado: RegistroPrincipal.alumnosInscripcion){
            
            cb_alumno.addItem(alumnoAgregado);
            
        }
        
        
    }
    
    

}






