/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Materia;

/**
 *
 * @author Rickert
 */
public class AltaMaterias extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaMaterias
     */
    public AltaMaterias() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_ventanaMaterias = new javax.swing.JPanel();
        lbl_titulom = new javax.swing.JLabel();
        lbl_codigo = new javax.swing.JLabel();
        lbl_anom = new javax.swing.JLabel();
        lbl_nombrem = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_nombrem = new javax.swing.JTextField();
        txt_anom = new javax.swing.JTextField();
        btn_nuevom = new javax.swing.JButton();
        btn_guardarm = new javax.swing.JButton();
        btn_salirm = new javax.swing.JButton();

        pnl_ventanaMaterias.setBackground(new java.awt.Color(204, 204, 204));
        pnl_ventanaMaterias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulom.setFont(new java.awt.Font("JetBrains Mono NL Medium", 0, 14)); // NOI18N
        lbl_titulom.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulom.setText("Formulario de Materias");
        pnl_ventanaMaterias.add(lbl_titulom, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 6, -1, -1));

        lbl_codigo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_codigo.setText("CODIGO:");
        pnl_ventanaMaterias.add(lbl_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 50, -1, -1));

        lbl_anom.setForeground(new java.awt.Color(0, 0, 0));
        lbl_anom.setText("AÑO:");
        pnl_ventanaMaterias.add(lbl_anom, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 139, -1, -1));

        lbl_nombrem.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nombrem.setText("NOMBRE:");
        pnl_ventanaMaterias.add(lbl_nombrem, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 93, -1, -1));
        pnl_ventanaMaterias.add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 47, 185, -1));
        pnl_ventanaMaterias.add(txt_nombrem, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 90, 185, -1));

        txt_anom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_anomActionPerformed(evt);
            }
        });
        pnl_ventanaMaterias.add(txt_anom, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 139, 185, -1));

        btn_nuevom.setText("NUEVO");
        btn_nuevom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevomActionPerformed(evt);
            }
        });
        pnl_ventanaMaterias.add(btn_nuevom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        btn_guardarm.setText("GUARDAR");
        btn_guardarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarmActionPerformed(evt);
            }
        });
        pnl_ventanaMaterias.add(btn_guardarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 90, -1));

        btn_salirm.setText("SALIR");
        btn_salirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirmActionPerformed(evt);
            }
        });
        pnl_ventanaMaterias.add(btn_salirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(pnl_ventanaMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(pnl_ventanaMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_anomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_anomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_anomActionPerformed

    private void btn_nuevomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevomActionPerformed

        txt_codigo.setText("");
        txt_anom.setText("");
        txt_nombrem.setText("");

    }//GEN-LAST:event_btn_nuevomActionPerformed

    private void btn_guardarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarmActionPerformed

        int codigoMateria = Integer.parseInt(txt_codigo.getText());
        int anoMateria = Integer.parseInt(txt_anom.getText());
        String nombreMateria = txt_nombrem.getText();

        Materia materiaCreada = new Materia(codigoMateria, nombreMateria, anoMateria);

        RegistroPrincipal.materiasInscripcion.add(materiaCreada);

    }//GEN-LAST:event_btn_guardarmActionPerformed

    private void btn_salirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirmActionPerformed

        pnl_ventanaMaterias.removeAll();
        pnl_ventanaMaterias.repaint();

        pnl_ventanaMaterias.setVisible(false);
        this.dispose();
        // ACA HAY QUE SEGUIR

    }//GEN-LAST:event_btn_salirmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardarm;
    private javax.swing.JButton btn_nuevom;
    private javax.swing.JButton btn_salirm;
    private javax.swing.JLabel lbl_anom;
    private javax.swing.JLabel lbl_codigo;
    private javax.swing.JLabel lbl_nombrem;
    private javax.swing.JLabel lbl_titulom;
    private javax.swing.JPanel pnl_ventanaMaterias;
    private javax.swing.JTextField txt_anom;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_nombrem;
    // End of variables declaration//GEN-END:variables
}
