/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Alumno;

/**
 *
 * @author Rickert
 */
public class AltaAlumnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaAlumnos
     */
    public AltaAlumnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_ventanaAlumnos = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        lbl_legajo = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        lbl_apellido = new javax.swing.JLabel();
        txt_legajo = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        btn_nuevo = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        pnl_ventanaAlumnos.setBackground(new java.awt.Color(153, 153, 153));
        pnl_ventanaAlumnos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo.setFont(new java.awt.Font("JetBrains Mono NL Medium", 0, 14)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_titulo.setText("Formulario de alumnos");
        pnl_ventanaAlumnos.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 6, -1, -1));

        lbl_legajo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_legajo.setText("LEGAJO:");
        pnl_ventanaAlumnos.add(lbl_legajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 50, -1, -1));

        lbl_nombre.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nombre.setText("NOMBRE:");
        pnl_ventanaAlumnos.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 139, -1, -1));

        lbl_apellido.setForeground(new java.awt.Color(0, 0, 0));
        lbl_apellido.setText("APELLIDO:");
        pnl_ventanaAlumnos.add(lbl_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 93, -1, -1));
        pnl_ventanaAlumnos.add(txt_legajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 47, 185, -1));
        pnl_ventanaAlumnos.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 90, 185, -1));

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        pnl_ventanaAlumnos.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 139, 185, -1));

        btn_nuevo.setText("NUEVO");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        pnl_ventanaAlumnos.add(btn_nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        pnl_ventanaAlumnos.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 90, -1));

        btn_salir.setText("SALIR");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        pnl_ventanaAlumnos.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(pnl_ventanaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnl_ventanaAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        
        txt_legajo.setText("");
        txt_nombre.setText("");
        txt_apellido.setText("");
        
        
        
        
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        
        int legajoAlumno = Integer.parseInt(txt_legajo.getText());
        String nombreAlumno = txt_nombre.getText();
        String apellidoAlumno = txt_apellido.getText();
        
        Alumno alumnoCreado = new Alumno(legajoAlumno, nombreAlumno, apellidoAlumno);
        
        
        RegistroPrincipal.alumnosInscripcion.add(alumnoCreado);
        
        
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        
        
        pnl_ventanaAlumnos.removeAll();
        pnl_ventanaAlumnos.repaint();
        
   
        
        pnl_ventanaAlumnos.setVisible(false);
        // ACA HAY QUE SEGUIR
        
        
    }//GEN-LAST:event_btn_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel lbl_apellido;
    private javax.swing.JLabel lbl_legajo;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JPanel pnl_ventanaAlumnos;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_legajo;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
