
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rickert
 */
public class Conversor extends javax.swing.JFrame {

    /**
     * Creates new form Conversor
     */
    public Conversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btng_botones = new javax.swing.ButtonGroup();
        pnl_fondo = new javax.swing.JPanel();
        pnl_ventana = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        txt_registro = new javax.swing.JTextField();
        btn_fah = new javax.swing.JRadioButton();
        btn_kelvin = new javax.swing.JRadioButton();
        btn_radianes = new javax.swing.JRadioButton();
        btn_celsius = new javax.swing.JRadioButton();
        lbl_tituloPrincipal = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnl_fondo.setBackground(new java.awt.Color(51, 51, 51));
        pnl_fondo.setForeground(new java.awt.Color(102, 102, 102));
        pnl_fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_ventana.setBackground(new java.awt.Color(204, 204, 204));

        lbl_titulo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo.setText("Ingrese temperatura en grados: ");

        txt_registro.setBackground(new java.awt.Color(204, 204, 204));
        txt_registro.setForeground(new java.awt.Color(0, 0, 0));
        txt_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_registroActionPerformed(evt);
            }
        });

        btng_botones.add(btn_fah);
        btn_fah.setForeground(new java.awt.Color(0, 0, 0));
        btn_fah.setText("Fahrenheit");

        btng_botones.add(btn_kelvin);
        btn_kelvin.setForeground(new java.awt.Color(0, 0, 0));
        btn_kelvin.setText("Kelvin");
        btn_kelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kelvinActionPerformed(evt);
            }
        });

        btng_botones.add(btn_radianes);
        btn_radianes.setForeground(new java.awt.Color(0, 0, 0));
        btn_radianes.setText("Radianes");
        btn_radianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_radianesActionPerformed(evt);
            }
        });

        btng_botones.add(btn_celsius);
        btn_celsius.setForeground(new java.awt.Color(0, 0, 0));
        btn_celsius.setText("Celsius");
        btn_celsius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_celsiusActionPerformed(evt);
            }
        });

        lbl_tituloPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_tituloPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tituloPrincipal.setText("Conversor de Temperatura");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/actualizar.png"))); // NOI18N
        jButton1.setText("Convertir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/481431.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kelvin.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/farenheit.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/radio.png"))); // NOI18N

        javax.swing.GroupLayout pnl_ventanaLayout = new javax.swing.GroupLayout(pnl_ventana);
        pnl_ventana.setLayout(pnl_ventanaLayout);
        pnl_ventanaLayout.setHorizontalGroup(
            pnl_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ventanaLayout.createSequentialGroup()
                .addGroup(pnl_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_ventanaLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_ventanaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnl_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnl_ventanaLayout.createSequentialGroup()
                        .addGroup(pnl_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_ventanaLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnl_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_celsius)
                                    .addComponent(btn_radianes)))
                            .addGroup(pnl_ventanaLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(pnl_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_ventanaLayout.createSequentialGroup()
                                        .addComponent(btn_kelvin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1))
                                    .addGroup(pnl_ventanaLayout.createSequentialGroup()
                                        .addComponent(btn_fah)
                                        .addGap(11, 11, 11)
                                        .addComponent(jLabel3)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pnl_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))))
                .addGap(42, 42, 42))
            .addGroup(pnl_ventanaLayout.createSequentialGroup()
                .addComponent(lbl_tituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_ventanaLayout.setVerticalGroup(
            pnl_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ventanaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl_tituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl_ventanaLayout.createSequentialGroup()
                        .addComponent(txt_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(pnl_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_kelvin)
                            .addComponent(btn_celsius)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(25, 25, 25)
                        .addGroup(pnl_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ventanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btn_fah)
                                .addComponent(jLabel3))
                            .addComponent(btn_radianes)))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_fondo.add(pnl_ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 320, 320));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        double valorTemperatura = Double.parseDouble(txt_registro.getText());
        
        
        if(btn_celsius.isSelected()){
            JOptionPane.showMessageDialog(this, "La temperatura en celsius es de: " + valorTemperatura); 
        } else if(btn_kelvin.isSelected()){
            double temperaturaKelvin = (valorTemperatura + 273.15);
            JOptionPane.showMessageDialog(this, "La temperatura en kelvin es de: " + temperaturaKelvin); 
        } else if(btn_fah.isSelected()){
            double temperaturaFah = (valorTemperatura * 9 / 5 + 32);
            JOptionPane.showMessageDialog(this, "La temperatura en fahrenheit es de: " + temperaturaFah); 
        } else{
            double temperaturaRadianes = (valorTemperatura * (3.14 / 180));
            JOptionPane.showMessageDialog(this, "La temperatura en radianes es de: " + temperaturaRadianes); 
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_celsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_celsiusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_celsiusActionPerformed

    private void btn_radianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_radianesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_radianesActionPerformed

    private void btn_kelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kelvinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_kelvinActionPerformed

    private void txt_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_registroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_registroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btn_celsius;
    private javax.swing.JRadioButton btn_fah;
    private javax.swing.JRadioButton btn_kelvin;
    private javax.swing.JRadioButton btn_radianes;
    private javax.swing.ButtonGroup btng_botones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_tituloPrincipal;
    private javax.swing.JPanel pnl_fondo;
    private javax.swing.JPanel pnl_ventana;
    private javax.swing.JTextField txt_registro;
    // End of variables declaration//GEN-END:variables
}
