/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Producto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rickert
 */
public class listaPrecio extends javax.swing.JInternalFrame {

    private DefaultTableModel tablaPrecios = new DefaultTableModel(){
        
        public boolean isCellEditable(int f, int c){
            return false;
        }
        
    };;
    
    /**
     * Creates new form listaPrecio
     */
    public listaPrecio() {
        initComponents();
        cargarPreciosTabla();
        
        
    }

    public void cargarPreciosTabla(){
        
        tablaPrecios.addColumn("Codigo");
        tablaPrecios.addColumn("Descripcion");
        tablaPrecios.addColumn("Precio");
        tablaPrecios.addColumn("Categoria");
        tablaPrecios.addColumn("Stock");
    
        tbl_tablaPrecio.setModel(tablaPrecios);
        
        
        
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tituloPrecio = new javax.swing.JLabel();
        lbl_entrePrecio = new javax.swing.JLabel();
        txt_entrePrecio1 = new javax.swing.JTextField();
        lbl_entreyPrecio = new javax.swing.JLabel();
        txt_entrePrecio2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tablaPrecio = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lbl_tituloPrecio.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_tituloPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tituloPrecio.setText("Listado Por Precio");

        lbl_entrePrecio.setForeground(new java.awt.Color(0, 0, 0));
        lbl_entrePrecio.setText("Entre $");

        lbl_entreyPrecio.setForeground(new java.awt.Color(0, 0, 0));
        lbl_entreyPrecio.setText("y");

        txt_entrePrecio2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_entrePrecio2KeyReleased(evt);
            }
        });

        tbl_tablaPrecio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_tablaPrecio);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lbl_tituloPrecio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lbl_entrePrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_entrePrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_entreyPrecio)
                        .addGap(18, 18, 18)
                        .addComponent(txt_entrePrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_tituloPrecio)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_entrePrecio)
                    .addComponent(txt_entrePrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_entreyPrecio)
                    .addComponent(txt_entrePrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_entrePrecio2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_entrePrecio2KeyReleased
        
        tablaPrecios.setRowCount(0);
        
        if(txt_entrePrecio1.getText().isEmpty() || txt_entrePrecio2.getText().isEmpty()){
            System.out.println("No se activa el filtrador aun");
        } else{
            
            try{
                
                for(Producto p: vistaMenuPrincipal.listaProductos.getListaProductos()){
            
                if(p.getPrecio() >= Double.parseDouble(txt_entrePrecio1.getText()) && p.getPrecio() <= Double.parseDouble(txt_entrePrecio2.getText())){
                
                        tablaPrecios.addRow(new Object[]{
                            p.getCodigo(),
                            p.getDescripcion(),
                            p.getPrecio(),
                            p.getRubro(),
                            p.getStock()
                        });
                
                
                    }
                }
                
                
            } catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Solo puede ingresar numeros");
            }
            
        }
        
        
    }//GEN-LAST:event_txt_entrePrecio2KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_entrePrecio;
    private javax.swing.JLabel lbl_entreyPrecio;
    private javax.swing.JLabel lbl_tituloPrecio;
    private javax.swing.JTable tbl_tablaPrecio;
    private javax.swing.JTextField txt_entrePrecio1;
    private javax.swing.JTextField txt_entrePrecio2;
    // End of variables declaration//GEN-END:variables
}
