/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Producto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rickert
 */
public class listaRubro extends javax.swing.JInternalFrame {

    private DefaultTableModel tablaRubro = new DefaultTableModel(){
        
        public boolean isCellEditable(int f, int c){
            return false;
        }
        
    };;
    
    
    /**
     * Creates new form listaRubro
     */
    public listaRubro() {
        initComponents();
        cargarRubrosTabla();
        cargarRubrosCategorias();
    }

    public void cargarRubrosCategorias(){
        
        
        vistaMenuPrincipal.categoriasProductos.clear();
        vistaMenuPrincipal.categoriasProductos.add("Comestible");
        vistaMenuPrincipal.categoriasProductos.add("Limpieza");
        vistaMenuPrincipal.categoriasProductos.add("Perfumeria");
        
        
        jcb_rubroLista.removeAllItems();
        for(String categoria: vistaMenuPrincipal.categoriasProductos){
            
            jcb_rubroLista.addItem(categoria);
            
            
        }
        
        
        
    }
    
    
    public void cargarRubrosTabla(){
        
        tablaRubro.addColumn("Codigo");
        tablaRubro.addColumn("Descripcion");
        tablaRubro.addColumn("Precio");
        tablaRubro.addColumn("Categoria");
        tablaRubro.addColumn("Stock");
    
        tbl_tablaRubro.setModel(tablaRubro);
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tituloRubro = new javax.swing.JLabel();
        lbl_infoRubro = new javax.swing.JLabel();
        jcb_rubroLista = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_tablaRubro = new javax.swing.JTable();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        lbl_tituloRubro.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tituloRubro.setText("Listado Por Rubro");

        lbl_infoRubro.setForeground(new java.awt.Color(0, 0, 0));
        lbl_infoRubro.setText("Rubro");

        jcb_rubroLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_rubroListaActionPerformed(evt);
            }
        });

        tbl_tablaRubro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_tablaRubro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_infoRubro)
                                .addGap(50, 50, 50)
                                .addComponent(jcb_rubroLista, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_tituloRubro)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lbl_tituloRubro)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_infoRubro)
                    .addComponent(jcb_rubroLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_rubroListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_rubroListaActionPerformed
        
        tablaRubro.setRowCount(0);
        
        String rubroFiltro = (String) jcb_rubroLista.getSelectedItem();
        
        for(Producto p: vistaMenuPrincipal.listaProductos.getListaProductos()){
            
            if(p.getRubro().equalsIgnoreCase(rubroFiltro)){
                
                tablaRubro.addRow(new Object[]{
                            p.getCodigo(),
                            p.getDescripcion(),
                            p.getPrecio(),
                            p.getRubro(),
                            p.getStock()
                });
            }
          
            
            
        }
       
    }//GEN-LAST:event_jcb_rubroListaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcb_rubroLista;
    private javax.swing.JLabel lbl_infoRubro;
    private javax.swing.JLabel lbl_tituloRubro;
    private javax.swing.JTable tbl_tablaRubro;
    // End of variables declaration//GEN-END:variables
}
