/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Contacto;
import java.util.Map;
import javax.swing.DefaultListModel;

/**
 *
 * @author Rickert
 */
public class BuscarCliente extends javax.swing.JInternalFrame {
//cambios en la interfaz hechos

    /**
     * Creates new form BuscarCliente
     */
    public BuscarCliente() {
        initComponents();
        llenarListaTelefonos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_busquedaClientes = new javax.swing.JPanel();
        lbl_tituloClientes = new javax.swing.JLabel();
        lbl_telefonoCliente = new javax.swing.JLabel();
        txt_telefonoClienteBusqueda = new javax.swing.JTextField();
        lbl_dniClienteBusqueda = new javax.swing.JLabel();
        lbl_apellidoClientesBusqueda = new javax.swing.JLabel();
        lbl_nombreClientesBusqueda = new javax.swing.JLabel();
        lbl_ciudadClienteBusqueda = new javax.swing.JLabel();
        lbl_domicilioClienteBusqueda = new javax.swing.JLabel();
        txt_dniClientesBusqueda = new javax.swing.JTextField();
        txt_apellidoClientesBusqueda = new javax.swing.JTextField();
        txt_nombreClientesBusqueda = new javax.swing.JTextField();
        txt_ciudadClientesBusqueda = new javax.swing.JTextField();
        txt_domicilioClientesBusqueda = new javax.swing.JTextField();
        btn_salirBusquedaClientes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlist_telefonosAgregados = new javax.swing.JList<>();

        pnl_busquedaClientes.setBackground(new java.awt.Color(204, 204, 204));
        pnl_busquedaClientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_tituloClientes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_tituloClientes.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tituloClientes.setText("Busqueda de Clientes:");

        lbl_telefonoCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbl_telefonoCliente.setText("Telefono:");

        lbl_dniClienteBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        lbl_dniClienteBusqueda.setText("DNI:");

        lbl_apellidoClientesBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        lbl_apellidoClientesBusqueda.setText("Apellido:");

        lbl_nombreClientesBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nombreClientesBusqueda.setText("Nombre:");

        lbl_ciudadClienteBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        lbl_ciudadClienteBusqueda.setText("Ciudad:");

        lbl_domicilioClienteBusqueda.setForeground(new java.awt.Color(0, 0, 0));
        lbl_domicilioClienteBusqueda.setText("Domicilio:");

        btn_salirBusquedaClientes.setText("Salir");
        btn_salirBusquedaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirBusquedaClientesActionPerformed(evt);
            }
        });

        jlist_telefonosAgregados.setName(""); // NOI18N
        jlist_telefonosAgregados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlist_telefonosAgregadosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlist_telefonosAgregados);

        javax.swing.GroupLayout pnl_busquedaClientesLayout = new javax.swing.GroupLayout(pnl_busquedaClientes);
        pnl_busquedaClientes.setLayout(pnl_busquedaClientesLayout);
        pnl_busquedaClientesLayout.setHorizontalGroup(
            pnl_busquedaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_busquedaClientesLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnl_busquedaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnl_busquedaClientesLayout.createSequentialGroup()
                        .addComponent(lbl_telefonoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_telefonoClienteBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(lbl_dniClienteBusqueda))
                    .addGroup(pnl_busquedaClientesLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(pnl_busquedaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_apellidoClientesBusqueda, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_nombreClientesBusqueda, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_ciudadClienteBusqueda, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_domicilioClienteBusqueda, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(31, 31, 31)
                .addGroup(pnl_busquedaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_dniClientesBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(txt_apellidoClientesBusqueda)
                    .addComponent(txt_nombreClientesBusqueda)
                    .addComponent(txt_ciudadClientesBusqueda)
                    .addComponent(txt_domicilioClientesBusqueda))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_busquedaClientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_busquedaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_busquedaClientesLayout.createSequentialGroup()
                        .addComponent(lbl_tituloClientes)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_busquedaClientesLayout.createSequentialGroup()
                        .addComponent(btn_salirBusquedaClientes)
                        .addContainerGap())))
        );
        pnl_busquedaClientesLayout.setVerticalGroup(
            pnl_busquedaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_busquedaClientesLayout.createSequentialGroup()
                .addGroup(pnl_busquedaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_busquedaClientesLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbl_tituloClientes)
                        .addGap(28, 28, 28)
                        .addGroup(pnl_busquedaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_telefonoCliente)
                            .addComponent(txt_telefonoClienteBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_dniClienteBusqueda)
                            .addComponent(txt_dniClientesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_busquedaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_apellidoClientesBusqueda)
                            .addComponent(txt_apellidoClientesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(pnl_busquedaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_nombreClientesBusqueda)
                            .addComponent(txt_nombreClientesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(pnl_busquedaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_ciudadClienteBusqueda)
                            .addComponent(txt_ciudadClientesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnl_busquedaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_domicilioClienteBusqueda)
                            .addComponent(txt_domicilioClientesBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_busquedaClientesLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btn_salirBusquedaClientes)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(pnl_busquedaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(pnl_busquedaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlist_telefonosAgregadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlist_telefonosAgregadosValueChanged

        txt_telefonoClienteBusqueda.setText(String.valueOf(jlist_telefonosAgregados.getSelectedValue()));
        txt_dniClientesBusqueda.setText(String.valueOf(frmMenuPrincipal.frmdirectorio.buscarContacto(jlist_telefonosAgregados.getSelectedValue()).getDni()));
        txt_apellidoClientesBusqueda.setText(String.valueOf(frmMenuPrincipal.frmdirectorio.buscarContacto(jlist_telefonosAgregados.getSelectedValue()).getApellido()));
        txt_nombreClientesBusqueda.setText(String.valueOf(frmMenuPrincipal.frmdirectorio.buscarContacto(jlist_telefonosAgregados.getSelectedValue()).getNombre()));
        txt_ciudadClientesBusqueda.setText(String.valueOf(frmMenuPrincipal.frmdirectorio.buscarContacto(jlist_telefonosAgregados.getSelectedValue()).getCiudad()));
        txt_domicilioClientesBusqueda.setText(String.valueOf(frmMenuPrincipal.frmdirectorio.buscarContacto(jlist_telefonosAgregados.getSelectedValue()).getDireccion()));
        
        
    }//GEN-LAST:event_jlist_telefonosAgregadosValueChanged

    private void btn_salirBusquedaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirBusquedaClientesActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirBusquedaClientesActionPerformed

    public void llenarListaTelefonos() {

        DefaultListModel<Long> modelo = new DefaultListModel<>();
        
        for(Long telefono: frmMenuPrincipal.frmdirectorio.getDirectorio().keySet()){
            
            if(telefono.toString().contains(txt_telefonoClienteBusqueda.getText())){
                modelo.addElement(Long.valueOf(telefono.toString()));
            }
            
        }
        
        
        
        jlist_telefonosAgregados.setModel(modelo);
    
        
    
    }
    

    /*
    
    
    
    
    
    
    
    
    */   
                
                
    //frmMenuPrincipal.frmdirectorio.getDirectorio().keySet();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_salirBusquedaClientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Long> jlist_telefonosAgregados;
    private javax.swing.JLabel lbl_apellidoClientesBusqueda;
    private javax.swing.JLabel lbl_ciudadClienteBusqueda;
    private javax.swing.JLabel lbl_dniClienteBusqueda;
    private javax.swing.JLabel lbl_domicilioClienteBusqueda;
    private javax.swing.JLabel lbl_nombreClientesBusqueda;
    private javax.swing.JLabel lbl_telefonoCliente;
    private javax.swing.JLabel lbl_tituloClientes;
    private javax.swing.JPanel pnl_busquedaClientes;
    private javax.swing.JTextField txt_apellidoClientesBusqueda;
    private javax.swing.JTextField txt_ciudadClientesBusqueda;
    private javax.swing.JTextField txt_dniClientesBusqueda;
    private javax.swing.JTextField txt_domicilioClientesBusqueda;
    private javax.swing.JTextField txt_nombreClientesBusqueda;
    private javax.swing.JTextField txt_telefonoClienteBusqueda;
    // End of variables declaration//GEN-END:variables
}
