/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Contacto;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USURIO
 */
public class BuscarTelefonoApellido extends javax.swing.JInternalFrame {
private DefaultTableModel modelo = new DefaultTableModel();
    public BuscarTelefonoApellido() {
        initComponents();
       llenarTitulos();
       llenarListaApellidos();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlTituloApellido = new javax.swing.JLabel();
        txt_apellidobuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatosTelefono = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaApellidos = new javax.swing.JList<>();

        jlTituloApellido.setText("Apellido");

        txt_apellidobuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_apellidobuscarKeyReleased(evt);
            }
        });

        tablaDatosTelefono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaDatosTelefono);

        listaApellidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaApellidosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaApellidos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTituloApellido)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txt_apellidobuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jlTituloApellido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_apellidobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaApellidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaApellidosValueChanged
     String apellidoSeleccionado = listaApellidos.getSelectedValue();
      

        modelo.setRowCount(0); // limpiamos tabla

        for (Map.Entry<Long, Contacto> entry : frmMenuPrincipal.frmdirectorio.getDirectorio().entrySet()) {
            Contacto c = entry.getValue();

            if (c.getApellido().equalsIgnoreCase(apellidoSeleccionado)) {
                modelo.addRow(new Object[]{
                    c.getDni(),
                    c.getApellido(),
                    c.getNombre(),
                    c.getDireccion(),
                    c.getCiudad(),
                    String.valueOf(entry.getKey())
                        });
            }
        }
    
    }//GEN-LAST:event_listaApellidosValueChanged

    private void txt_apellidobuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_apellidobuscarKeyReleased
       
  
    }//GEN-LAST:event_txt_apellidobuscarKeyReleased

    public void llenarTitulos(){
         modelo.addColumn("Dni");
        modelo.addColumn("Apellido");
        modelo.addColumn("Nombre");
        modelo.addColumn("Direccion");
        modelo.addColumn("Ciudad");
        modelo.addColumn("Telefono");
        
        tablaDatosTelefono.setModel(modelo);
    }
    
public void llenarListaApellidos(){
    String texto = txt_apellidobuscar.getText();
    
    DefaultListModel<String> modeloLista = new DefaultListModel<>();
      for (Contacto c : frmMenuPrincipal.frmdirectorio.getDirectorio().values()) {
          if (c.getApellido().toLowerCase().contains(texto)){
    modeloLista.addElement(c.getApellido());
        }
      }
       listaApellidos.setModel(modeloLista);
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlTituloApellido;
    private javax.swing.JList<String> listaApellidos;
    private javax.swing.JTable tablaDatosTelefono;
    private javax.swing.JTextField txt_apellidobuscar;
    // End of variables declaration//GEN-END:variables
}
