/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import javax.swing.JOptionPane;

/**
 *
 * @author Rickert
 */
public class menu_agregarCiudad extends javax.swing.JInternalFrame {

    /**
     * Creates new form menu_agregarCiudad
     */
    public menu_agregarCiudad() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_panelAgregarCiudad = new javax.swing.JPanel();
        lbl_agregarciudadtitulo = new javax.swing.JLabel();
        lbl_nombreciudad = new javax.swing.JLabel();
        txt_valorAgregarCiudad = new javax.swing.JTextField();
        btn_guardarCiudad = new javax.swing.JButton();
        btn_salirCiudad = new javax.swing.JButton();

        jp_panelAgregarCiudad.setBackground(new java.awt.Color(204, 204, 204));

        lbl_agregarciudadtitulo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_agregarciudadtitulo.setText("Agregar Ciudad");

        lbl_nombreciudad.setForeground(new java.awt.Color(0, 0, 0));
        lbl_nombreciudad.setText("Nombre Ciudad:");

        btn_guardarCiudad.setText("Guardar");
        btn_guardarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarCiudadActionPerformed(evt);
            }
        });

        btn_salirCiudad.setText("Salir");
        btn_salirCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirCiudadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_panelAgregarCiudadLayout = new javax.swing.GroupLayout(jp_panelAgregarCiudad);
        jp_panelAgregarCiudad.setLayout(jp_panelAgregarCiudadLayout);
        jp_panelAgregarCiudadLayout.setHorizontalGroup(
            jp_panelAgregarCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_panelAgregarCiudadLayout.createSequentialGroup()
                .addGroup(jp_panelAgregarCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_panelAgregarCiudadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_guardarCiudad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_salirCiudad))
                    .addGroup(jp_panelAgregarCiudadLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(lbl_nombreciudad)
                        .addGap(18, 18, 18)
                        .addGroup(jp_panelAgregarCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_agregarciudadtitulo)
                            .addComponent(txt_valorAgregarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jp_panelAgregarCiudadLayout.setVerticalGroup(
            jp_panelAgregarCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_panelAgregarCiudadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_agregarciudadtitulo)
                .addGap(33, 33, 33)
                .addGroup(jp_panelAgregarCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nombreciudad)
                    .addComponent(txt_valorAgregarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_panelAgregarCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardarCiudad)
                    .addComponent(btn_salirCiudad))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jp_panelAgregarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jp_panelAgregarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void btn_guardarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarCiudadActionPerformed
        
        String valorDeCiudad = txt_valorAgregarCiudad.getText();
        
        
        frmMenuPrincipal.ciudadesData.add(valorDeCiudad);
        JOptionPane.showMessageDialog(this, "Se agrego la ciudad correctamente");
        
        txt_valorAgregarCiudad.setText("");
        
        
        
        
    }//GEN-LAST:event_btn_guardarCiudadActionPerformed

    private void btn_salirCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirCiudadActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirCiudadActionPerformed

    
    public void llenarComboCiudad(){
        
        
        
        
        
        
        
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardarCiudad;
    private javax.swing.JButton btn_salirCiudad;
    private javax.swing.JPanel jp_panelAgregarCiudad;
    private javax.swing.JLabel lbl_agregarciudadtitulo;
    private javax.swing.JLabel lbl_nombreciudad;
    private javax.swing.JTextField txt_valorAgregarCiudad;
    // End of variables declaration//GEN-END:variables
}
