/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Contacto;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Rickert
 */
public class menu_agregarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form menu_agregarCliente
     */
    public menu_agregarCliente() {
        initComponents();
        llenarComboCiudad();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_panelCliente = new javax.swing.JPanel();
        lbl_tituloCliente = new javax.swing.JLabel();
        lbl_dniCliente = new javax.swing.JLabel();
        lbl_NombreCliente = new javax.swing.JLabel();
        lbl_apellidoCliente = new javax.swing.JLabel();
        lbl_ciudadCliente = new javax.swing.JLabel();
        lbl_domicilioCliente = new javax.swing.JLabel();
        txt_dniCliente = new javax.swing.JTextField();
        txt_nombreCliente = new javax.swing.JTextField();
        txt_apellidoCliente = new javax.swing.JTextField();
        jcb_ciudadCliente = new javax.swing.JComboBox<>();
        txt_domicilioCliente = new javax.swing.JTextField();
        lbl_telefonoCliente = new javax.swing.JLabel();
        txt_telefonoCliente = new javax.swing.JTextField();
        btn_guardarCliente = new javax.swing.JButton();
        btn_salirCliente = new javax.swing.JButton();

        jp_panelCliente.setBackground(new java.awt.Color(204, 204, 204));
        jp_panelCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbl_tituloCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_tituloCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tituloCliente.setText("Agregar Cliente");

        lbl_dniCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbl_dniCliente.setText("DNI:");

        lbl_NombreCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbl_NombreCliente.setText("Nombre:");

        lbl_apellidoCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbl_apellidoCliente.setText("Apellido:");

        lbl_ciudadCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbl_ciudadCliente.setText("Ciudad:");

        lbl_domicilioCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbl_domicilioCliente.setText("Domicilio:");

        jcb_ciudadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_ciudadClienteActionPerformed(evt);
            }
        });

        lbl_telefonoCliente.setForeground(new java.awt.Color(0, 0, 0));
        lbl_telefonoCliente.setText("Telefono:");

        btn_guardarCliente.setText("Guardar");
        btn_guardarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarClienteMouseClicked(evt);
            }
        });
        btn_guardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarClienteActionPerformed(evt);
            }
        });

        btn_salirCliente.setText("Salir");
        btn_salirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_panelClienteLayout = new javax.swing.GroupLayout(jp_panelCliente);
        jp_panelCliente.setLayout(jp_panelClienteLayout);
        jp_panelClienteLayout.setHorizontalGroup(
            jp_panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_panelClienteLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jp_panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_NombreCliente)
                    .addComponent(lbl_dniCliente)
                    .addComponent(lbl_apellidoCliente)
                    .addComponent(lbl_ciudadCliente)
                    .addComponent(lbl_domicilioCliente)
                    .addComponent(lbl_telefonoCliente))
                .addGap(40, 40, 40)
                .addGroup(jp_panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_panelClienteLayout.createSequentialGroup()
                        .addGroup(jp_panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_dniCliente)
                            .addComponent(txt_nombreCliente)
                            .addComponent(txt_apellidoCliente)
                            .addComponent(txt_domicilioCliente)
                            .addGroup(jp_panelClienteLayout.createSequentialGroup()
                                .addComponent(txt_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 48, Short.MAX_VALUE)))
                        .addGap(65, 65, 65))
                    .addGroup(jp_panelClienteLayout.createSequentialGroup()
                        .addComponent(jcb_ciudadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jp_panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_guardarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_salirCliente)
                .addContainerGap())
            .addGroup(jp_panelClienteLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(lbl_tituloCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_panelClienteLayout.setVerticalGroup(
            jp_panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tituloCliente)
                .addGap(18, 18, 18)
                .addGroup(jp_panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_dniCliente)
                    .addComponent(txt_dniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NombreCliente)
                    .addComponent(txt_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_apellidoCliente)
                    .addComponent(txt_apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcb_ciudadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_ciudadCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jp_panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_domicilioCliente)
                    .addComponent(txt_domicilioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_telefonoCliente)
                    .addComponent(txt_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_guardarCliente)
                    .addComponent(btn_salirCliente))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(141, Short.MAX_VALUE)
                .addComponent(jp_panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jp_panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_ciudadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_ciudadClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_ciudadClienteActionPerformed

    private void btn_guardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarClienteActionPerformed
        
        String dniUsuario = txt_dniCliente.getText();
        String nombreUsuario = txt_nombreCliente.getText();
        String apellidoUsuario = txt_apellidoCliente.getText();
        String ciudadUsuario = (String) jcb_ciudadCliente.getSelectedItem();
        String domicilioUsuario = txt_domicilioCliente.getText();
        Long telefonoUsuario = Long.valueOf(txt_telefonoCliente.getText());
        
        Contacto contactoCreado = new Contacto(dniUsuario, nombreUsuario, apellidoUsuario, ciudadUsuario, domicilioUsuario);
        frmMenuPrincipal.frmdirectorio.agregarContacto(telefonoUsuario, contactoCreado);
        
        JOptionPane.showMessageDialog(this, "Se agrego correctamente el cliente en el directorio");
        
        txt_dniCliente.setText("");
        txt_nombreCliente.setText("");
        txt_apellidoCliente.setText("");
        txt_domicilioCliente.setText("");
        txt_telefonoCliente.setText("");
        
        
        
    }//GEN-LAST:event_btn_guardarClienteActionPerformed

    private void btn_salirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirClienteActionPerformed
        
       this.dispose();
        
        
    }//GEN-LAST:event_btn_salirClienteActionPerformed

    private void btn_guardarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarClienteMouseClicked
       
    }//GEN-LAST:event_btn_guardarClienteMouseClicked

    
    
    public void llenarComboCiudad(){
        
        for(String ciudadRecorrida: frmMenuPrincipal.ciudadesData){
            
            jcb_ciudadCliente.addItem(ciudadRecorrida);
            
        }
        
    
        
        
        
        
        
        
        
        
        
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardarCliente;
    private javax.swing.JButton btn_salirCliente;
    private javax.swing.JComboBox<String> jcb_ciudadCliente;
    private javax.swing.JPanel jp_panelCliente;
    private javax.swing.JLabel lbl_NombreCliente;
    private javax.swing.JLabel lbl_apellidoCliente;
    private javax.swing.JLabel lbl_ciudadCliente;
    private javax.swing.JLabel lbl_dniCliente;
    private javax.swing.JLabel lbl_domicilioCliente;
    private javax.swing.JLabel lbl_telefonoCliente;
    private javax.swing.JLabel lbl_tituloCliente;
    private javax.swing.JTextField txt_apellidoCliente;
    private javax.swing.JTextField txt_dniCliente;
    private javax.swing.JTextField txt_domicilioCliente;
    private javax.swing.JTextField txt_nombreCliente;
    private javax.swing.JTextField txt_telefonoCliente;
    // End of variables declaration//GEN-END:variables
}
