/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Contacto;
import Modelo.DirectorioTelefonico;
import Vistas.frmMenuPrincipal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Map;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USURIO
 */
public class menuBuscarClienteCiudad extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form menuBuscarClienteCiudad
     */
    public menuBuscarClienteCiudad() {
       
 initComponents();
    titulosTabla();    
    llenadoCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLtitulo = new javax.swing.JLabel();
        jLtituloCiudades = new javax.swing.JLabel();
        jcmb_ciudades = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablitaciudad = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();

        jLtitulo.setText("Buscar cliente de directorio por ciudad");

        jLtituloCiudades.setText("Ciudades:");

        jcmb_ciudades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcmb_ciudadesItemStateChanged(evt);
            }
        });
        jcmb_ciudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb_ciudadesActionPerformed(evt);
            }
        });

        jtablitaciudad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtablitaciudad);

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLtitulo)
                .addGap(139, 139, 139))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbSalir)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLtituloCiudades)
                            .addComponent(jcmb_ciudades, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLtitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLtituloCiudades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcmb_ciudades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jbSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmb_ciudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb_ciudadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmb_ciudadesActionPerformed
private DefaultTableModel modelito = new DefaultTableModel();
public void titulosTabla(){
 modelito.addColumn("Dni");
    modelito.addColumn("Apellido");
    modelito.addColumn("Nombre");
    modelito.addColumn("Direccion");
    modelito.addColumn("Ciudad");
    modelito.addColumn("Telefono");
    jtablitaciudad.setModel(modelito);

}





    private void jcmb_ciudadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcmb_ciudadesItemStateChanged
   if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        String ciudadElegida = (String) jcmb_ciudades.getSelectedItem();
        modelito.setRowCount(0);

       
        for (Map.Entry<Long, Contacto> entry : frmMenuPrincipal.frmdirectorio.getDirectorio().entrySet()) {
            Contacto c = entry.getValue();
            if (c.getCiudad().equalsIgnoreCase(ciudadElegida)) {
                modelito.addRow(new Object[]{
                    c.getDni(),
                    c.getApellido(),
                    c.getNombre(),
                    c.getDireccion(),
                    c.getCiudad(),
                    entry.getKey()   
                });
            }
        }

        jtablitaciudad.setModel(modelito);
    }
    }//GEN-LAST:event_jcmb_ciudadesItemStateChanged

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
this.dispose();       
    }//GEN-LAST:event_jbSalirActionPerformed
   
    public void llenarTabla(){
        
    }
    
    
    public void llenadoCombo(){
        jcmb_ciudades.removeAllItems(); 
      for (String ciudades : frmMenuPrincipal.ciudadesData){
          
          jcmb_ciudades.addItem(ciudades);
          
      }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLtitulo;
    private javax.swing.JLabel jLtituloCiudades;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcmb_ciudades;
    private javax.swing.JTable jtablitaciudad;
    // End of variables declaration//GEN-END:variables
}
