/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Modelo.Contacto;
import java.util.Map;
import static java.util.Map.entry;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rickert
 */
public class menu_borrarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form menu_borrarCliente
     */
    public menu_borrarCliente() {
        initComponents();
        cargarColumnas();
        llenarListaTelefonos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tituloBorrar = new javax.swing.JLabel();
        lbl_dniBorrar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlist_listaClientesBorrar = new javax.swing.JList<>();
        txt_dniBorrar = new javax.swing.JTextField();
        btn_borrar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_tablaClientesBorrar = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        lbl_tituloBorrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_tituloBorrar.setForeground(new java.awt.Color(0, 0, 0));
        lbl_tituloBorrar.setText("Borrar Cliente");

        lbl_dniBorrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_dniBorrar.setForeground(new java.awt.Color(0, 0, 0));
        lbl_dniBorrar.setText("DNI: ");

        jlist_listaClientesBorrar.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jlist_listaClientesBorrarValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jlist_listaClientesBorrar);

        btn_borrar.setText("Borrar Cliente/s");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        tbl_tablaClientesBorrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_tablaClientesBorrar);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(lbl_tituloBorrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_dniBorrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_dniBorrar)))
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 290, Short.MAX_VALUE)
                        .addComponent(btn_borrar)
                        .addGap(147, 147, 147)
                        .addComponent(btn_salir)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tituloBorrar)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_dniBorrar)
                            .addComponent(lbl_dniBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_borrar)
                    .addComponent(btn_salir))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlist_listaClientesBorrarValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jlist_listaClientesBorrarValueChanged
        
        String dniSeleccionado = jlist_listaClientesBorrar.getSelectedValue();
        txt_dniBorrar.setText(jlist_listaClientesBorrar.getSelectedValue());
        
        modeloTabla.setRowCount(0);
        
        for(Map.Entry<Long, Contacto> cr: frmMenuPrincipal.frmdirectorio.getDirectorio().entrySet()){
            
            if(cr.getValue().getDni().equals(dniSeleccionado)){
                
                modeloTabla.addRow(new Object[]{
                cr.getValue().getDni(),
                cr.getValue().getApellido(),
                cr.getValue().getNombre(),
                cr.getValue().getDireccion(),
                cr.getValue().getCiudad(),
                String.valueOf(cr.getKey())
                });
               
            }
            
            
        }
        
        
    }//GEN-LAST:event_jlist_listaClientesBorrarValueChanged

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        
        
        String dniSeleccionadoBorrar = jlist_listaClientesBorrar.getSelectedValue();
        
        
        for(Map.Entry<Long, Contacto> cr: frmMenuPrincipal.frmdirectorio.getDirectorio().entrySet()){
            
            if(cr.getValue().getDni().equals(dniSeleccionadoBorrar)){
                
                frmMenuPrincipal.frmdirectorio.borrarContacto(cr.getKey());
                
                
            }
            
            modelo.removeElement(dniSeleccionadoBorrar);
        }
        
        JOptionPane.showMessageDialog(this, "Se borro el contacto con exito");
        modeloTabla.setRowCount(0);
        
        // tomar en cuenta excepcion al borrar 
        
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    
    private DefaultListModel<String> modelo = new DefaultListModel<>();
    
    
    public void llenarListaTelefonos() {

        
        
        for(Contacto telefono: frmMenuPrincipal.frmdirectorio.getDirectorio().values()){
            
            
            modelo.addElement(telefono.getDni());
            
        }
        
        
       
        
        jlist_listaClientesBorrar.setModel(modelo);
    
        
    
    }
    
    
    
    public void cargarColumnas(){
        
        modeloTabla.addColumn("Dni");
        modeloTabla.addColumn("Apellido");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Direccion");
        modeloTabla.addColumn("Ciudad");
        modeloTabla.addColumn("Telefono");
        
        tbl_tablaClientesBorrar.setModel(modeloTabla);
        
        
        
        
    };
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> jlist_listaClientesBorrar;
    private javax.swing.JLabel lbl_dniBorrar;
    private javax.swing.JLabel lbl_tituloBorrar;
    private javax.swing.JTable tbl_tablaClientesBorrar;
    private javax.swing.JTextField txt_dniBorrar;
    // End of variables declaration//GEN-END:variables
}
